<?php

echo('<div class="page-title">
    <h1>Su pedido ha finalizado con fallos.</h1></div>
	<h2 class="sub-title">Gracias por su confianza!</h2>
	Pulse el botón si desea realizar otro pedido.');

echo('<div class="buttons-set">
    <a href="'.Mage::getBaseUrl().'"><button type="button" class="button" title="Continue Shopping" ><span><span>Continue Shopping</span></span></button></a>
	</div>');

?>
